### ISSUE TITLE
sync find_inlets code after the hacking day modification

### ISSUE THREAD

**Issue by yanliu-chn** [cybergis/nfie-floodmap#1]
it seems the code you improved after hacking is not in github. could you merge the change?

Also, I still see one outlet as output of the dangle code. I remember Xing suggested using NHDPlus info to decide outlets/inlets. It is especially important for large watersheds. Could you find a way to do that?

**Comment by ahmetartu** [comment]
I pushed my recent changes. Now the tool is removing all outlet points among dangle points in NHDPlus vector data, using stream order information in the file.

**Comment by yanliu-chn** [comment]
you used "gdal/ogr_core.h" which caused compile time error. that header file is already to move gdal's top include dir. which GDAL version were you using to compile in your dev env?

Also, don't close this issue yet. I need Xing to look at it. Thanks!

**Comment by yanliu-chn** [comment]
btw, i fixed the header file issue. now it compiles.

**Comment by ahmetartu** [comment]
It's using gdal2 functions. So you need to add module of gdal2-stack to compile it on ROGER.

**Comment by yanliu-chn** [comment]
whether it's gdal2 or gdal1, on linux, all the header files are in $GDAL_HOME/include. There is not subdir `gdal` in the include dir. So you can't use `#include "gdal/ogr_core.h"`. I fixed it.
