### ISSUE TITLE
buffer solution to edge contamination

### ISSUE THREAD

**Issue by yanliu-chn** [cybergis/nfie-floodmap#5]
To address the edge contamination issue, we will provide a buffering option into the workflow script.

- does the DEM need to be buffered?
- does the flowline shp need to be buffered?

**Comment by dtarb** [comment]
Yes the DEM should be buffered.  It is better in general to never clip DEMs to the watershed boundary, and instead let the algorithms determine the boundary from the DEM.  Flowline shp does not need to be buffered.

**Comment by yanliu-chn** [comment]
added 1km buffer in dem clipping. the clipping distance (in degree unit) can be set using environment variable.
