### ISSUE TITLE
TauDEM VRT output error: bounding box incorrect

### ISSUE THREAD

**Issue by yanliu-chn** [cybergis/nfie-floodmap#7]
HUC12 was broken at aread8. It was because the d8 vrt has wrong coordinates:
<pre>
[root@cg-gpu01 tx]# gdalinfo txp.vrt
Driver: VRT/Virtual Raster
Files: txp.vrt
       /gpfs/largeblockFS/scratch/nfie/tx/txpp0.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp1.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp2.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp3.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp4.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp5.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp6.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp7.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp8.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp9.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp10.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp11.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp12.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp13.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp14.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp15.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp16.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp17.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp18.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp19.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp20.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp21.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp22.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp23.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp24.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp25.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp26.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp27.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp28.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp29.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp30.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp31.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp32.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp33.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp34.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp35.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp36.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp37.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp38.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp39.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp40.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp41.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp42.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp43.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp44.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp45.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp46.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp47.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp48.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp49.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp50.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp51.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp52.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp53.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp54.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp55.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp56.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp57.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp58.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp59.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp60.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp61.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp62.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp63.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp64.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp65.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp66.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp67.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp68.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp69.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp70.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp71.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp72.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp73.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp74.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp75.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp76.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp77.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp78.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp79.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp80.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp81.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp82.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp83.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp84.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp85.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp86.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp87.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp88.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp89.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp90.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp91.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp92.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp93.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp94.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp95.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp96.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp97.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp98.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp99.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp100.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp101.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp102.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp103.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp104.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp105.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp106.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp107.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp108.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp109.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp110.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp111.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp112.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp113.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp114.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp115.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp116.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp117.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp118.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp119.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp120.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp121.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp122.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp123.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp124.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp125.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp126.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp127.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp128.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp129.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp130.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp131.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp132.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp133.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp134.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp135.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp136.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp137.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp138.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp139.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp140.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp141.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp142.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp143.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp144.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp145.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp146.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp147.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp148.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp149.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp150.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp151.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp152.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp153.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp154.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp155.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp156.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp157.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp158.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp159.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp160.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp161.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp162.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp163.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp164.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp165.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp166.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp167.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp168.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp169.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp170.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp171.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp172.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp173.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp174.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp175.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp176.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp177.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp178.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp179.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp180.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp181.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp182.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp183.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp184.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp185.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp186.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp187.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp188.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp189.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp190.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp191.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp192.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp193.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp194.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp195.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp196.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp197.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp198.tiff
       /gpfs/largeblockFS/scratch/nfie/tx/txpp199.tiff
Size is 115825, 95413
Coordinate System is:
GEOGCS["NAD83",
    DATUM["North_American_Datum_1983",
        SPHEROID["GRS 1980",6378137,298.2572221010002,
            AUTHORITY["EPSG","7019"]],
        AUTHORITY["EPSG","6269"]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433],
    AUTHORITY["EPSG","4269"]]
Origin = (0.000000000000000,0.000000000000000)
Pixel Size = (0.000092592744424,-0.000092592551491)
Corner Coordinates:
Upper Left  (   0.0000000,   0.0000000) (  0d 0' 0.01"E,  0d 0' 0.01"N)
Lower Left  (   0.0000000,  -8.8345331) (  0d 0' 0.01"E,  8d50' 4.32"S)
Upper Right (  10.7245546,   0.0000000) ( 10d43'28.40"E,  0d 0' 0.01"N)
Lower Right (  10.7245546,  -8.8345331) ( 10d43'28.40"E,  8d50' 4.32"S)
Center      (   5.3622773,  -4.4172666) (  5d21'44.20"E,  4d25' 2.16"S)
Band 1 Block=128x128 Type=Int16, ColorInterp=Gray
  NoData Value=-32768
</pre>

Please verify VRT output correctness by doing more testing. The correct coord info should be:
<pre>
Origin = (-103.870533495000004,34.688973274299997)
Pixel Size = (0.000092592744424,-0.000092592551491)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (-103.8705335,  34.6889733) (103d52'13.92"W, 34d41'20.30"N)
Lower Left  (-103.8705335,  25.8544402) (103d52'13.92"W, 25d51'15.98"N)
Upper Right ( -93.1459789,  34.6889733) ( 93d 8'45.52"W, 34d41'20.30"N)
Lower Right ( -93.1459789,  25.8544402) ( 93d 8'45.52"W, 25d51'15.98"N)
Center      ( -98.5082562,  30.2717067) ( 98d30'29.72"W, 30d16'18.14"N)
</pre>

**Comment by ahmetartu** [comment]
The issue is fixed and pushed into the blockdecomp branch.

**Comment by yanliu-chn** [comment]
could you please describe the bug and how it's fixed?

**Comment by ahmetartu** [comment]
The bug was that the algorithm was not considering the topleft x, y of the input DEM in the calculation of the coordinates, but only using relative coordinates at global buffer. So now the calculation is fixed.

**Comment by yanliu-chn** [comment]
@ahmetartu Could you rerun the whole NED10m on ROGER? We want to test the scalability of the new D8 code on NED 10m, but we need the pit removed DEM input.

**Comment by kornholi** [comment]
I think the "incorrect" 10m NED should work fine for testing, since only the origin is calculated incorrectly. There are still some things to tune for D8, I tried to run half of the dataset and it was still struggling (however that half might have had much more than 50% of the flats of the whole NED).

**Comment by ahmetartu** [comment]
I submitted the job but the origin error should have no effect on D8 performance or result, except it should also produce DEM files with wrong origins.

The DEMs with wrong origin are located at "/gpfs_scratch/taudem-ahmet/runs/usned10" and the correct DEMs will be at "/gpfs_scratch/taudem-ahmet/runs/usned10/corrected"
